//
// Created by referencecat on 07.02.24.
//

#ifndef UNNAMEDSPACESTRATEGY_ORBITALMECHANICSENGINE_H
#define UNNAMEDSPACESTRATEGY_ORBITALMECHANICSENGINE_H


class OrbitalMechanicsEngine {

};


#endif //UNNAMEDSPACESTRATEGY_ORBITALMECHANICSENGINE_H
